# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  App\Domain\Auth\Security\BannedUserChecker: ~
  App\Domain\Auth\Security\LoginAttemptsUserChecker: ~

  App\Domain\Auth\Security\CompositeUserChecker:
    arguments:
      $checkers:
        - '@App\Domain\Auth\Security\BannedUserChecker'
        - '@App\Domain\Auth\Security\LoginAttemptsUserChecker'

  app.auth.login_rate_limiter:
    class: Symfony\Component\Security\Http\RateLimiter\DefaultLoginRateLimiter
    arguments:
      $globalFactory: '@limiter.auth_login_ip'
      $localFactory: '@limiter.auth_login_username_ip'
      $secret: '%kernel.secret%'