# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  App\Foundation\Captcha\Contract\CaptchaSolutionStoreInterface:
    alias: App\Foundation\Captcha\Store\CacheCaptchaSolutionStore

  App\Foundation\Captcha\Contract\CaptchaRegistryInterface:
    alias: App\Foundation\Captcha\CaptchaRegistry

  App\Foundation\Captcha\CaptchaRegistry:
    arguments:
      $challenges: !tagged_locator { tag: 'app.captcha.challenge', index_by: 'type' }
      $generators: !tagged_locator { tag: 'app.captcha.generator', index_by: 'type' }

  App\Foundation\Captcha\Puzzle\PuzzleCaptchaChallenge:
    tags:
      - { name: 'app.captcha.challenge', type: 'puzzle' }

  App\Foundation\Captcha\Puzzle\PuzzleGenerator:
    arguments:
      $rootImage: '%kernel.project_dir%/public/images/puzzles'
      $imageCount: 5
    tags:
      - { name: 'app.captcha.generator', type: 'puzzle' }