# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  App\Foundation\Security\Contract\TokenGeneratorInterface:
    alias: App\Foundation\Security\TokenGeneratorService

  App\Foundation\Security\Contract\TokenHasherInterface:
    alias: App\Foundation\Security\TokenHasher

  App\Foundation\Security\TokenHasher:
    arguments:
      $secret: '%kernel.secret%'