# config/packages/rate_limiter.yaml
framework:
  rate_limiter:
    limiters:
      resend_confirmation_short:
        policy: 'fixed_window'
        limit: 2
        interval: '10 minutes'

      resend_confirmation_long:
        policy: 'fixed_window'
        limit: 5
        interval: '1 hour'

      resend_confirmation_email:
        policy: 'compound'
        limiters:
          - resend_confirmation_short
          - resend_confirmation_long

      auth_login_username_ip:
        policy: token_bucket
        limit: 5
        rate:
          interval: '15 minutes'
          amount: 5

      auth_login_ip:
          policy: sliding_window
          limit: 25
          interval: '15 minutes'