twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        '%kernel.project_dir%/src/Foundation/Maker/templates': maker

when@test:
    twig:
        strict_variables: true
