controllers:
    resource:
        path: ../src/Http/Controller/
        namespace: App\Http\Controller
    type: attribute
dashboard_controllers:
    name_prefix: dashboard.
    prefix: '%dashboard_prefix%'
    resource:
        path: ../src/Http/dashboard/Controller/
        namespace: App\Http\Dashboard\Controller
    type: attribute
