# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    dkim_key: '%env(resolve:default::MAILER_DKIM)%'
    dashboard_prefix: '%env(resolve:DASHBOARD_PREFIX)%'
    app.vite.manifest_path: '%kernel.project_dir%/public/assets/.vite/manifest.json'
    app.assets.public_base_path: '/assets'
    app.vite.dev_server_url: 'https://localhost:3000'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $devServerUrl: '%app.vite.dev_server_url%'
            string $publicBasePath: '%app.assets.public_base_path%'
            string $rootProjectDir: '%kernel.project_dir%'
            string $secret: '%kernel.secret%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Foundation/Migrations/'
            - '../src/Tests/'
            - '../src/Kernel.php'
            - '../src/Foundation/Captcha/CaptchaRegistry.php'
            - '../src/Domain/Auth/Security/CompositeUserChecker.php'
            - '../src/Foundation/Bridge/ManifestReader.php'
            - '../src/Foundation/Bridge/Resolver/EnvironmentAssetResolver.php'

imports:
    - { resource: services/assets.yaml }
    - { resource: services/auth.yaml }
    - { resource: services/captcha.yaml } # HERE!
    - { resource: services/security.yaml }
    - { resource: services/controllers.yaml }
    - { resource: services/twig.yaml }