# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
# Prod
parameters:
  app.assets.public_base_path: '/assets'
  app.vite.manifest_path: '%kernel.project_dir%/public/assets/.vite/manifest.json'
  app.vite.manifest_cache_key: 'vite_manifest'