# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

#  App\Foundation\Captcha\Contract\CaptchaSolutionStoreInterface:
 # '@App\Foundation\Captcha\Store\CacheCaptchaSolutionStore'